version: '2'
services:
  yadm:
    image: formapro/nginx-php-fpm:latest-all-exts
    working_dir: /yadm
    depends_on:
      - mongo
    volumes:
      - ./:/yadm
    environment:
      - MONGODB_URI=mongodb://mongo/yadm_test

  mongo:
    image: mongo:4
    ports:
      - "27017:27017"
